// Central mock data store — the single source of truth for all static/seed data.
// Replace this file's exports with Supabase queries when doing the backend integration.
import { CATEGORY_CATALOG } from './categoryCatalog';
import { VendorProfile } from '../types';

export const MOCK_CATEGORIES = CATEGORY_CATALOG;

export const MOCK_LOCALITIES = [
  {
    id: 1,
    name: 'Yaba / Lagos Mainland',
    state: 'Lagos, Nigeria',
    registered_users_count: 942,
    center_location: { latitude: 6.5034, longitude: 3.3714 },
  },
  {
    id: 2,
    name: 'Wuse II / Abuja Central',
    state: 'FCT, Nigeria',
    registered_users_count: 1045,
    center_location: { latitude: 9.0765, longitude: 7.3986 },
  },
  {
    id: 3,
    name: 'Accra Central',
    state: 'Greater Accra, Ghana',
    registered_users_count: 780,
    center_location: { latitude: 5.6037, longitude: -0.1870 },
  },
  {
    id: 4,
    name: 'Nairobi CBD',
    state: 'Nairobi, Kenya',
    registered_users_count: 620,
    center_location: { latitude: -1.2921, longitude: 36.8219 },
  },
  {
    id: 5,
    name: 'Johannesburg Central',
    state: 'Gauteng, South Africa',
    registered_users_count: 530,
    center_location: { latitude: -26.2041, longitude: 28.0473 },
  },
];

export const MOCK_VENDORS: VendorProfile[] = [
  {
    id: 'v1',
    business_name: "Mama Titi's Kitchen",
    bio: "Authentic Nigerian home-cooked meals — Jollof rice, Egusi soup, Pounded Yam, and daily specials. Delivered fresh with love.",
    category: 'Food & Catering',
    sub_category: 'Home-Cooked Meals',
    rating: 4.8,
    is_open: true,
    is_home_based: true,
    locality_id: 1,
    subscription_tier: 2,
    business_hours: '08:00 AM - 09:00 PM',
    image: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=500&q=80',
    street_address: 'Alagomeji Street, Yaba, Lagos',
    point_wallet: 150,
    handshake_count: 124,
    avg_response_mins: 8,
    portfolio_urls: [
      'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=500&q=80',
      'https://images.unsplash.com/photo-1567620817605-d2c986d30421?w=500&q=80',
    ],
    exact_location: { latitude: 6.5050, longitude: 3.3750 },
    services: [
      {
        id: 's1',
        title: 'Full Jollof Rice Pack',
        description: 'Generous portion of smoky party jollof rice with choice of protein (chicken, fish, or beef) and coleslaw.',
        category: 'Meals',
        price: 2500,
        stock: 20,
        stockStatus: 'in_stock',
        image: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=300&q=80',
        allowPointDiscount: true,
        pointsDiscountCost: 50,
        discountValue: '10%'
      },
      {
        id: 's2',
        title: 'Egusi Soup (Family Pot)',
        description: 'Rich, aromatic Egusi soup with assorted meat, stockfish and dried prawns. Serves 4–6.',
        category: 'Soups',
        price: 7000,
        stock: 5,
        stockStatus: 'in_stock',
        image: 'https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=300&q=80',
      },
    ],
  },
  {
    id: 'v2',
    business_name: 'FlowFix Plumbing & Waterworks',
    bio: "Lagos's most trusted plumbers. Same-day service for leaks, burst pipes, blocked drains, and full bathroom installations.",
    category: 'Home Services',
    sub_category: 'Plumbing',
    rating: 4.6,
    is_open: true,
    is_home_based: false,
    locality_id: 2,
    subscription_tier: 1,
    business_hours: '09:00 AM - 05:00 PM',
    image: 'https://images.unsplash.com/photo-1607400201515-c2c41c07d307?w=500&q=80',
    street_address: 'Toyin Street, Ikeja, Lagos',
    point_wallet: 45,
    handshake_count: 56,
    avg_response_mins: 15,
    portfolio_urls: [
      'https://images.unsplash.com/photo-1607400201515-c2c41c07d307?w=500&q=80',
    ],
    exact_location: { latitude: 6.5985, longitude: 3.3512 },
    services: [
      {
        id: 's3',
        title: 'Emergency Leak Repair',
        description: 'Rapid same-day response for burst pipes, overflowing tanks, or any urgent water emergency.',
        category: 'Emergency',
        price: 15000,
        stock: 99,
        stockStatus: 'in_stock',
        image: 'https://images.unsplash.com/photo-1607400201515-c2c41c07d307?w=300&q=80',
      },
    ],
  },
  {
    id: 'v3',
    business_name: 'GlowUp Braids & Beauty',
    bio: "Premium braid styles, twist-outs, and natural hair care in the comfort of your location. Book your session today!",
    category: 'Beauty & Personal Care',
    sub_category: 'Hair Braiding',
    rating: 4.9,
    is_open: true,
    is_home_based: true,
    locality_id: 1,
    subscription_tier: 2,
    business_hours: '10:00 AM - 08:00 PM',
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=500&q=80',
    street_address: 'Herbert Macaulay Way, Yaba',
    point_wallet: 320,
    handshake_count: 210,
    avg_response_mins: 4,
    portfolio_urls: [
      'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=500&q=80',
      'https://images.unsplash.com/photo-1519762822-dea94f2a5a4e?w=500&q=80',
    ],
    exact_location: { latitude: 6.5101, longitude: 3.3640 },
    services: [
      {
        id: 's4',
        title: 'Knotless Box Braids (Medium)',
        description: 'Stylish, protective knotless box braids. Medium length. Includes scalp prep and finishing oil.',
        category: 'Braiding',
        price: 18000,
        stock: 3,
        stockStatus: 'in_stock',
        image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=300&q=80',
        allowPointDiscount: true,
        pointsDiscountCost: 100,
        discountValue: 'N2,000 Off'
      },
      {
        id: 's5',
        title: 'Full Wash & Condition',
        description: 'Deep cleanse, hot-oil treatment, and blow-dry.',
        category: 'Hair Care',
        price: 5500,
        stock: 10,
        stockStatus: 'in_stock',
        image: 'https://images.unsplash.com/photo-1519762822-dea94f2a5a4e?w=300&q=80',
      },
    ],
  },
  {
    id: 'v4',
    business_name: 'Tech Fix Hub',
    bio: 'Fast, affordable laptop and mobile phone repairs. Same-day screen replacements, data recovery, and software support.',
    category: 'Technology & Repairs',
    sub_category: 'Phone & Laptop Repair',
    rating: 4.5,
    is_open: false,
    is_home_based: false,
    locality_id: 3,
    subscription_tier: 1,
    business_hours: '09:00 AM - 06:00 PM',
    image: 'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=500&q=80',
    street_address: 'Admiralty Way, Lekki Phase 1',
    point_wallet: 10,
    handshake_count: 32,
    avg_response_mins: 25,
    portfolio_urls: [
      'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=500&q=80',
    ],
    exact_location: { latitude: 6.4401, longitude: 3.4714 },
    services: [
      {
        id: 's6',
        title: 'Screen Replacement (iPhone)',
        description: 'OEM-quality screen replacement for iPhone models. Includes 30-day warranty.',
        category: 'Repairs',
        price: 45000,
        stock: 8,
        stockStatus: 'in_stock',
        image: 'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=300&q=80',
      },
    ],
  },
];
